- name: cart configure
  hosts: cart
  become: yes
  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: create system cart roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system cart"
    - name: delete app directory
      ansible.builtin.file:
        path: /app
        state: absent
        mode: '0755'

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'
    - name: delete cart code
      ansible.builtin.file:
        path: /tmp/cart.zip
        state: absent

    - name: download cart code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
        dest: /tmp/cart.zip

    - name: unzip cart code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: install nodejs dependencies
      ansible.builtin.command: npm install  
      args:
        chdir: /app
    
    - name: create systemd service file
      ansible.builtin.template:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: copy mongo repo
      ansible.builtin.template:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    
    - name: check products loaded
      ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("cart")'
      register: cart_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ cart_output }}"

    - name: load the products
      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
      when: cart_output.stdout  | int < 0  
    
    - name: daemon reload
      ansible.builtin.systemd_service:
      daemon_reload: true

    - name: start cart
      ansible.builtin.service:
        name: cart
        state: restarted
        enabled: yes
