- name: catalogue configure
  hosts: catalogue
  become: yes
  tasks:
    - name: enable nodejs 20
      ansible.builtin.command: dnf module enable nodejs:20

    - name: install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: present
    
    - name: create system user roboshop
      ansible.builtin.user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin
        comment: "roboshop system user"
    - name: delete app directory
      ansible.builtin.file:
        path: /app
        state: absent
        mode: '0755'

    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        mode: '0755'
    - name: delete catalogue code
      ansible.builtin.file:
        path: /tmp/catalogue.zip
        state: absent

    - name: download catalogue code
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: unzip catalogue code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: install nodejs dependencies
      ansible.builtin.command: npm install  
      args:
        chdir: /app
    
    - name: create systemd service file
      ansible.builtin.template:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: copy mongo repo
      ansible.builtin.template:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongodb.repo

    - name: install mongodb client
      ansible.builtin.dnf:
        name: mongodb-mongosh
        state: present
    
    - name: check products loaded
      ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet  --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
      register: catalogue_output

    - name: print the output
      ansible.builtin.debug:
        msg: "{{ catalogue_output }}"

    - name: load the products
      ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
      when: catalogue_output.stdout  | int < 0  

    - name: start catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes
