- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enable nginx 1.24
    ansible.builtin.command: dnf module enable nginx:1.24 -y
      
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove default nginx content
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend content
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
      dest: /tmp/frontend.zip

  - name: unzip frontend content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes

  - name: remove default nginx configure
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy nginx configure
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.systemd:
      name: nginx
      state: restarted
      enabled: yes

  

  