- name: create ec2 and route53 records
  hosts: all
  connection: local
  vars:
    sg_id: "sg-04afc53a2f45b85cc"
    ami_id: "ami-0220d79f3f480ecf5"
    domain_name: "neelimadevops.online."
    env: "dev"
    action: "create"
    instances: 
    - mongodb
    - catalogue 
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "my-ec2-instance"
        security_group: "{{ sg_id }}"
        instance_type: "t3.micro"
        image_id: "{{ ami_id }}"
        name: "{{ item }}-{{env}}"
        tags: 
          Project: roboshop
          Component: "{{ item }}"
          Environment: "{{ env }}"
          Name: "{{ item }}-{{env}}"
        loop: "{{ instances }}"
        register: ec2_output
        when : action == "create"

    - name: print ec2 ec2_output
      ansible.builtin.debug: 
        msg: " print {{ ec2_output }}"

    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        wait: false
        loop: "{{ ec2_output.results}}"
        when: action == "create"

    # create route53 record for fronend as roboshop.dev.neelimadevops.online
    - name: create route53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "roboshop.{{ env }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].public_ip_address }}"
        wait: true
        loop: "{{ ec2_output.results}}"
        when: 
        - item.item == "frontend"
        - action == "create"


# ansible-playbook -i localhost,   -e '{"instances":["mongodb","catalogue","redis","user","cart","mysql","shipping","rabbitmq","payment","frontend"]}'  -e action=destroy roboshop.yaml

  #ansible-playbook -i localhost roboshop.yml
  #pip install boto3
  # set authentication
  #aws configure #access key #secret key #region


   